// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkdbyldpaaeiagesedzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZGJ5bGRwYWFlaWFnZXNlZHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTk4MjAsImV4cCI6MjA2NjM3NTgyMH0.SO6Jsn7QXyhQ9o7sCvw7h9S-etaKXGGKPkvRsFkeNhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);